/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package miPaquete;

import org.junit.jupiter.api.Test;

import domain.*;
import workflow.*;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void testPOS() {
        assertTrue(false);
    }
}
